/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BookCard: typeof import('./components/BookCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SigInForm: typeof import('./components/SigInForm.vue')['default']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
    SigUpForm: typeof import('./components/sigUpForm.vue')['default']
    Waves: typeof import('./components/Waves.vue')['default']
  }
}
