/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sigin: typeof import('./components/sigin.vue')['default']
    SigIn: typeof import('./components/sigIn.vue')['default']
    SigInForm: typeof import('./components/sigInForm.vue')['default']
    SigUpForm: typeof import('./components/sigUpForm.vue')['default']
  }
}
