/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    BookCard: typeof import('./components/book/BookCard.vue')['default']
    BtnConfirmation: typeof import('./components/utils/dialogConfirm.vue')['default']
    ButtonMenu: typeof import('./components/layout/buttonMenu.vue')['default']
    DialogConfirm: typeof import('./components/utils/dialogConfirm.vue')['default']
    GoogleBtn: typeof import('./components/login/googleBtn.vue')['default']
    InputPassword: typeof import('./components/login/inputPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/login/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/login/SignUpForm.vue')['default']
    Waves: typeof import('./components/layout/Waves.vue')['default']
  }
}
