/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/book/list-book': RouteRecordInfo<'/book/list-book', '/book/list-book', Record<never, never>, Record<never, never>>,
    '/book/view-book': RouteRecordInfo<'/book/view-book', '/book/view-book', Record<never, never>, Record<never, never>>,
    '/list-to-read': RouteRecordInfo<'/list-to-read', '/list-to-read', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my-reviews': RouteRecordInfo<'/my-reviews', '/my-reviews', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
  }
}
